# Generated by Django 6.0.7 on 2026-07-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_payment_guest_name_payment_reservation'),
        ('reservations', '0002_reservation_special_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Mpesa', 'Mpesa'), ('Cash', 'Cash'), ('Card', 'Card'), ('Bank', 'Bank Transfer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Paid', max_length=20),
        ),
    ]
