# Generated by Django 6.0.7 on 2026-07-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('Management', 'Management'), ('Reception', 'Reception'), ('Restaurant', 'Restaurant'), ('Housekeeping', 'Housekeeping'), ('Maintenance', 'Maintenance'), ('Security', 'Security')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_hired', models.DateField()),
            ],
        ),
    ]
