# Generated by Django 6.0.7 on 2026-08-07 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0008_reservation_check_in_time_reservation_check_out_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nights', models.IntegerField(default=1)),
                ('room_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('room_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
        ),
    ]
