# Generated by Django 6.0.7 on 2026-07-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
