# Generated by Django 6.0.7 on 2026-07-23 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('reservations', '0002_reservation_special_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='guest_name',
        ),
        migrations.AddField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation'),
            preserve_default=False,
        ),
    ]
