# Generated by Django 6.0.7 on 2026-07-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='guest_profiles/'),
        ),
    ]
