# Generated by Django 6.0.7 on 2026-08-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Cleaning', 'Cleaning'), ('Maintenance', 'Maintenance')], default='Available', max_length=20),
        ),
    ]
