# Generated by Django 6.0.7 on 2026-07-31 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_user'),
        ('rooms', '0004_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='room_type',
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
            preserve_default=False,
        ),
    ]
