# Generated by Django 6.0.7 on 2026-08-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoiceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(choices=[('Restaurant', 'Restaurant'), ('Laundry', 'Laundry'), ('Mini Bar', 'Mini Bar'), ('Spa', 'Spa'), ('Transport', 'Transport'), ('Other', 'Other')], max_length=50),
        ),
    ]
